#ifndef USERMAPSLAYERLIB_GLOBAL_H
#define USERMAPSLAYERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERMAPSLAYERLIB_LIBRARY)
#  define USERMAPSLAYER_API Q_DECL_EXPORT
#else
#  define USERMAPSLAYER_API Q_DECL_IMPORT
#endif

#endif //USERMAPSLAYERLIB_GLOBAL_H
